### ISSUE TITLE
Card locking

### ISSUE THREAD

**Issue by Breacher1337** [anttihaavikko/casual-crusade#1]
Hey! Nice game. However on a run I made there was a bug that caused a long run to end abruptly.
Having the powerup SIN causes unexpected behaviors. The cards become unplayable.

**Steps to reproduce:**

1. Have "SIN - Once per level, redraw your hand if stuck"
2. Play the last playable card (normally, this causes a life-loss/gameover, but causes a hand reroll instead with SIN)
3. Before the card shuffle, hold left click on any of the unplaceable cards
4. Have SIN proc, causing the reroll and finally cause the bug

**Notes**

- The unclickable card bug goes away if there aren't any more connectable tiles and the game goes to the next level
- The bug can be consistently reproduced based on the steps above.
- The bug can be avoided if the cards aren't held while SIN procs.

**Environment Details**

- Chrome 117
- Windows 10

**Comment by grandpa1946** [comment]
this is my record; what is a "long run"? 
![image](https://github.com/anttihaavikko/casual-crusade/assets/115040432/3ee374ad-291e-488d-bdf5-7f05067d0b35)

**Comment by anttihaavikko** [comment]
This is already fixed on the live version. The one on js13kgames will not change. You can find the current version on https://anttihaavikko.itch.io/casual-crusade
