### ISSUE TITLE
Incorrect pathfinding in larger maps

### ISSUE THREAD

**Issue by LianSheng197** [anttihaavikko/casual-crusade#2]
I'm not sure exactly why it happens, but every time I encounter bad pathfinding it's always in the later levels. (i.e. the larger maps)
I guess it has something to do with the large number of intersections.

Please refer to the video for specific error pathfinding.

https://github.com/anttihaavikko/casual-crusade/assets/18535495/fe96ef2e-d0d0-4429-af45-da896a9edb67

**Comment by anttihaavikko** [comment]
What do you think is wrong with it? It is the best scoring path I think as you have a skill allowing repeated steps on red tiles (limited to 5 if I remember correctly).

**Comment by LianSheng197** [comment]
I always thought it would find the shortest path...
So is the algorithm actually designed to find the highest-scoring path?

**Comment by anttihaavikko** [comment]
Yes indeed. I guess it could work with shortest too but the gameplay would be drastically different.

**Comment by LianSheng197** [comment]
Okay, it seems I misunderstood your design. Sorry.
